### ISSUE TITLE
Documentation breadcrumb trail for bootstrap, link is not working

### ISSUE THREAD

**Issue by jeanm182** [piotrmurach/loaf#31]
### Describe the problem
I'm using the docs way to use the breadcrumb_trail to display the breadcrumb using bootstrap v4.1, breadcrumb is displaying but links are not useful and current link is not with the class= "active" like it should be

### Steps to reproduce the problem
```<%= link_to_unless crumb.current?, crumb.name, crumb.url, (crumb.current? ? {'aria-current' => 'page'} : {}) %>


The actual workaround using link_to_unless_current instead crumb.current?
```<%= link_to_unless_current crumb.name, crumb.url, (crumb.current? ? {'aria-current' => 'page'} : {}) %>

That worked for me and thanks for providing this gem.

### Describe your environment

* OS version:  MacOs High Sierra
* Ruby version: 2.4.1
* Loaf version:  0.8.0

**Comment by piotrmurach** [comment]
Thanks for using the gem!

The bootstrap examples where provided by other contributors that used this gem. However, the usage of boostrap is accidental. The logic should work with any styling framework.

If I were you, I would probably investigate why `crumb.current?` doesn't work for you rather than choose to use `link_to unless_current` Rails method? This seems like you're masking some underlying issue in your code. 

Please bear in mind when you use `link_to_unless_current` you're essentially skipping behaviour of the `loaf` gem and letting Rails decide what is the current link! There is [a :match](https://github.com/piotrmurach/loaf#213-match) parameter that may help you set expected behaviour as to what is the current breadcrumb.

Hope this helps!
